import React from 'react';
import { Card, CardMedia, CardContent, Grid, Typography } from '@mui/material';
import Behle2021Card from '../../components/paper_cards/Behle2021';
import CEPLASCardnoexpand from '../../components/funders_cards/CEPLASCard_noexpand';
import BioSCCardnoexpand from '../../components/funders_cards/BioSCCard_noexpand';
import image from '../../components/images/digest_animation.gif';
import background from '../../components/images/background.png';


function Biosynthesis_Degredation(){
    return(

        <section>
        <div class="container-fluid">

            <Card sx={{ margin: "2em", marginTop: "1em", position:"relative" }}>
                    <CardMedia
                        height="300"
                        component="h1"
                        sx={{ color: "white", textAlign: "center", padding: "1em", fontSize: "4em", margin: "0" }}
                        image={background}
                    alt="A field of corn"   
                    >
                    <Typography variant="h2">
                    Cell Wall Biosynthesis & Degredation
                    </Typography></CardMedia>
            </Card>
            <Card sx={{ margin: "2em", marginTop: "1em", position:"relative" }}>
            <CardContent>
                <Typography variant="body 1" align='left' >
                Climate change directly impacts on plants, and specifically the plant cell wall is concerned. 
                Thus, we are interested in understanding how the structure and composition of the latter impacts on 
                the ability of the xylem to transport water under drought stress conditions. Besides, the plant cell 
                wall of leftover wastes generated by agriculture contains energy under the form of sugar polymers. In the context of energy shortage, we 
                tend to predict the recalcitrance of lignocellulose to saccharification, by taking into consideration its structure and composition.
                </Typography>
            </CardContent>
            </Card>
            <Card sx={{ margin: "2em", marginTop: "1em" }}>


            <Grid container justifyContent="space-around" spacing={1} padding="2em" sx={{position:"relative"}} alignItems="center" >
                <Grid item xs={4}>           

                        <CardContent>
                            <Typography variant="h5" align='left'>
                            The climate change directly impacts on plants, and specifically the plant cell wall is concerned. 
                            Thus, we are interested in understanding how the structure and composition of the latter impacts 
                            on the ability of the xylem to transport water under drought stress conditions. Besides, the plant 
                            cell wall of leftover wastes generated by agriculture contains energy under the form of sugar polymers. 
                            In the context of energy shortage, we tend to predict the recalcitrance of lignocellulose to saccharification, 
                            by taking into consideration its structure and composition.
                            </Typography>
                        </CardContent>
                    </Grid>
                    <Grid item xs={6} >

                        
                        <CardMedia
                        component="h1"
                        component="img"

                        sx={{ color: "white", textAlign: "center", padding: "1em", fontSize: "4em", margin: "0" }}
                        image={image}
                        alt="A gif of enzyme digestion simulations"></CardMedia>
                    </Grid>
                </Grid>
                <Grid container justifyContent="space-around" padding="2em" spacing={1} sx={{position:"relative"}}>
                    <Grid item>
                        <CEPLASCardnoexpand/>
                    </Grid>
                    <Grid item>
                        <BioSCCardnoexpand/>
                    </Grid>

                </Grid>
                </Card>

            <Behle2021Card/>
            </div>
        </section>
    );


}

export default Biosynthesis_Degredation;