name: Deploy React App

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'  # Specify your Node.js version here

      - name: Install dependencies
        run: |
          npm install

      - name: Build React app
        run: |
          npm run build
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts


      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "liannegahan@gmail.com"
          git config --global user.name "LianneGahan"
          git remote set-url origin git@github.com:${{ github.repository }}.git  # Use SSH URL
          npm run deploy